### ISSUE TITLE
CSS Eficiente

### ISSUE THREAD

**Issue by caiocss** [caiocss/FlowOfStudies#11]
### 2 - Seletores CSS
- [ ] Especificidade CSS
- [ ] Como seletores CSS são interpretados
- [ ] Não use IDs como seletores CSS
### 3 - CSS orientado a objetos
- [ ] Princípios básicos de CSS orientado a objetos
- [ ] Exemplos de objetos
- [ ] Conclusão
### 4 - SMACSS
- [ ] Introdução a SMACSS
- [ ] Nomenclatura
- [ ] Base
- [ ] Layout
- [ ] Módulo
- [ ] Estado
- [ ] Tema
- [ ] Mais exemplos da prática de SMACSS
- [ ] Conclusão
### 5 - BEM
- [ ] Pensando BEM
- [ ] Escrevendo BEM
- [ ] Conclusão
### 6 - Pré-processadores CSS
- [ ] O que são pré-processadores CSS?
- [ ] Aninhamento de regras
- [ ] Variáveis
- [ ] Mixins
- [ ] Extensão/Herança
- [ ] Importação
- [ ] Mais superpoderes de Sass
### 7 - CSS namespaces
- [ ] Os CSS namespaces mais comuns
- [ ] Conclusão
### 8 - Task Runners
- [ ] O que são Task Runners?
- [ ] Como instalar o Gulp
- [ ] Gulp API
- [ ] Exemplo de tarefas com Gulp
- [ ] Sugestões de plugins Gulp
- [ ] Conclusão'
### 9 - ITCSS
- [ ] O que é ITCSS?
- [ ] As camadas do triângulo invertido
- [ ] Organização do código com ITCSS
- [ ] Conclusão
### 10 - O fim
